name: Fullstack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    name: Run Spring Boot Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-tracker-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests
        run: ./mvnw test

  frontend-tests:
    name: Run Next.js (Jest) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job-tracker-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
