name: Fullstack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Run Spring Boot Tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./job-tracker-backend

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: jobtracker
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: uzonna
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run backend tests
        run: mvn test

  frontend:
    name: Run Frontend (Jest) Tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./job-tracker-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test
